@startuml Character
title The Mountain - Diagramme de Classe - Character

package Character {

    ' --- Nodes Godot de base ---
    class Node3D << (N,#FF2222) Godot >>
    class CharacterBody3D << (N,#FF2222) Godot >> {
        + _Ready()
        + _PhysicsProcess(delta: float)
    }
    enum CharacterRigState {
        Ragdoll
        Active
        Animated
        Static
    }
    ' --- Classes de jeu ---
    abstract class Character {
        + walkSpeed: float
        + model: Resource
        --
        + _PhysicsProcess(delta: float): void
        + TakeDamage(force: Vector3): void
        + _Ragdoll(force: Vector3): void
        +
        # _Die(): void
    }

    class Player {
        + peerId: int
        - camera: Camera3D
        - inputDir: Vector2
        --
        + _Input(event: InputEvent): void
        - _HandleMovement(): void
        + Interact(): void
    }

    class CharacterRig {
        + _BoneState : enum CharacterRigState
        + _ChangeState(CharacterRigState state)

    }

    ' --- Objets du monde ---
    class Interactable {
        + promptText: String
        --
        + Interact(player: Player): void
    }

    class CharacterUtils <<static>> {
        + {static} GetCharacterPos(character: Character): Vector3
        + {static} SendAction(action: PuzzleAction): bool
    }

    ' --- Hiérarchie ---
    Node3D <|-- CharacterBody3D
    CharacterBody3D <|-- Character : "Extends"
    Character <|-- Player : "Extends"
    Character <-- CharacterRig : "Est enfant dans \nla hiérarchie Godot"
    Player ..> Interactable : "Raycast / Area detection"

    note right of Character
        TakeDamage() passe le personnage
        en mode Ragdoll avec un vecteur
        de force amplifié dans sa direction
    end note

    note right of Interactable
        Implémentée par les éléments
        interactifs de la carte (puzzles,
        portes, objets...)
    end note
}

@enduml
